name: Build React Native App on Dispatch

on:
  repository_dispatch:
    types: [build-ios, build-android, build-both]
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'Target repository'
        required: true
        default: 'Kobumura/littletalks-mobile'
      platform:
        type: choice
        options: [ios, android, both]
        default: 'both'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      target_repo: ${{ steps.config.outputs.target_repo }}
      build_ios: ${{ steps.config.outputs.build_ios }}
      build_android: ${{ steps.config.outputs.build_android }}
    steps:
      - name: Configure Build
        id: config
        run: |
          if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            TARGET_REPO="${{ github.event.client_payload.target_repo }}"
            PLATFORM="${{ github.event.client_payload.platform || 'both' }}"
          else
            TARGET_REPO="${{ inputs.target_repo }}"
            PLATFORM="${{ inputs.platform || 'both' }}"
          fi
          
          echo "target_repo=$TARGET_REPO" >> $GITHUB_OUTPUT
          echo "build_ios=$([[ $PLATFORM == "ios" || $PLATFORM == "both" ]] && echo true || echo false)" >> $GITHUB_OUTPUT
          echo "build_android=$([[ $PLATFORM == "android" || $PLATFORM == "both" ]] && echo true || echo false)" >> $GITHUB_OUTPUT
          
          echo "🎯 Building $PLATFORM for $TARGET_REPO"

  ios-build:
    runs-on: macos-15
    needs: setup
    if: needs.setup.outputs.build_ios == 'true'
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ needs.setup.outputs.target_repo }}
          token: ${{ secrets.TARGET_REPO_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: iOS Build Placeholder
        run: |
          echo "🍎 iOS build running in PUBLIC repo = FREE MINUTES!"
          echo "Target: ${{ needs.setup.outputs.target_repo }}"
          echo "✅ This is working! Next we'll add real build steps."

  android-build:
    runs-on: buildjet-4vcpu-ubuntu-2204
    needs: setup
    if: needs.setup.outputs.build_android == 'true'
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ needs.setup.outputs.target_repo }}
          token: ${{ secrets.TARGET_REPO_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Android Build Placeholder
        run: |
          echo "🤖 Android build running in PUBLIC repo = FREE MINUTES!"
          echo "Target: ${{ needs.setup.outputs.target_repo }}"
          echo "✅ This is working! Next we'll add real build steps."