name: Test Fixed Fastlane Parameters

on:
  workflow_dispatch:
    inputs:
      bundle_id:
        description: 'iOS Bundle ID to test'
        required: true
        default: 'com.littletalks.app'

jobs:
  test-fixed-parameters:
    runs-on: ubuntu-latest
    steps:
      - name: Setup App Store Connect API Key
        run: |
          echo "🔑 Setting up App Store Connect API key..."
          
          # Create the P8 key file
          cat > /tmp/asc-api-key.p8 <<'EOF'
          -----BEGIN PRIVATE KEY-----
          MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQghnrjw2IY0M/VODiY
          k6Ex1H0W9jh2ws/5GXpwXTcF6xKgCgYIKoZIzj0DAQehRANCAARF2go6/YIvc5qz
          oeEsjfmxRtEWSdA7QQQKOYjSkD5SqwAWHuTSJfS+5mw/J4UcUNvRe4MwBRZ4FtBj
          hrCw4w+O
          -----END PRIVATE KEY-----
          EOF
          
          echo "ASC_API_KEY_ID=4QM5FBBF6P" >> $GITHUB_ENV
          echo "ASC_ISSUER_ID=63421d99-7718-41a8-99c8-01548625694f" >> $GITHUB_ENV
          echo "BUNDLE_ID=${{ inputs.bundle_id }}" >> $GITHUB_ENV

      - name: Install Fastlane
        run: |
          echo "📦 Installing Fastlane..."
          sudo gem install fastlane --no-document
          fastlane --version

      - name: Setup App Store Connect API Key Object (CORRECTED)
        run: |
          echo "🔐 Setting up App Store Connect API key object with correct parameters..."
          
          # Use CORRECT parameter names from debug output
          if RESULT=$(fastlane run app_store_connect_api_key \
              key_id:"$ASC_API_KEY_ID" \
              issuer_id:"$ASC_ISSUER_ID" \
              key_filepath:"/tmp/asc-api-key.p8" \
              duration:1200 \
              in_house:false 2>&1); then
          
            echo "✅ API key object created successfully!"
            echo "$RESULT"
          else
            echo "❌ API key object creation failed:"
            echo "$RESULT"
            exit 1
          fi

      - name: Test App Store Build Number Query (CORRECTED)
        run: |
          echo "🧪 Testing app_store_build_number with corrected parameters..."
          
          # Use the API key object (should now work)
          if RESULT=$(fastlane run app_store_build_number \
              app_identifier:"$BUNDLE_ID" 2>&1); then
          
            echo "✅ app_store_build_number SUCCEEDED!"
            echo "$RESULT"
            
            # Parse and show result
            PARSED_BUILD=$(echo "$RESULT" | grep -oE "(Result: |App Store build number: )?[0-9]+" | grep -oE "[0-9]+" | tail -1)
            echo ""
            echo "🎯 EXTRACTED BUILD NUMBER: $PARSED_BUILD"
            
            if [[ "$PARSED_BUILD" =~ ^[0-9]+$ ]] && [ "$PARSED_BUILD" -gt 0 ]; then
              echo "🎉 SUCCESS: Valid build number found!"
              echo "🔧 LP-21 SOLUTION: Use app_store_build_number with API key object"
            else
              echo "⚠️ Success but parsing needs adjustment"
            fi
            
          else
            echo "❌ app_store_build_number still failed:"
            echo "$RESULT"
          fi

      - name: Test TestFlight Build Number Query (CORRECTED)  
        run: |
          echo "🧪 Testing latest_testflight_build_number with corrected parameters..."
          
          if RESULT=$(fastlane run latest_testflight_build_number \
              app_identifier:"$BUNDLE_ID" 2>&1); then
          
            echo "✅ latest_testflight_build_number SUCCEEDED!"
            echo "$RESULT"
            
            # Parse and show result
            PARSED_BUILD=$(echo "$RESULT" | grep -oE "(Result: |build: )?[0-9]+" | grep -oE "[0-9]+" | tail -1)
            echo ""
            echo "🎯 EXTRACTED BUILD NUMBER: $PARSED_BUILD"
            
            if [[ "$PARSED_BUILD" =~ ^[0-9]+$ ]] && [ "$PARSED_BUILD" -gt 0 ]; then
              echo "🎉 SUCCESS: Valid build number found!"
              echo "🔧 LP-21 SOLUTION: Use latest_testflight_build_number with API key object"
            else
              echo "⚠️ Success but parsing needs adjustment"
            fi
            
          else
            echo "❌ latest_testflight_build_number failed:"
            echo "$RESULT"
          fi

      - name: Final LP-21 Solution
        run: |
          echo ""
          echo "🎯 LP-21 RESOLUTION SUMMARY"
          echo "=========================="
          echo ""
          echo "✅ ISSUE IDENTIFIED: Incorrect Fastlane parameter usage"
          echo "✅ SOLUTION: Use app_store_connect_api_key first, then query methods"
          echo ""
          echo "IMPLEMENTATION STEPS:"
          echo "1. Create API key object with app_store_connect_api_key"
          echo "2. Use app_identifier parameter (not individual key_id/issuer_id)"
          echo "3. API key object is automatically used by subsequent actions"
          echo ""
          echo "🔧 Update main workflow with corrected parameter usage"
          echo "🔧 Replace old individual parameters with API key object approach"
